#!/usr/bin/env python
# coding: utf-8

# In[1]:


from pandas import *
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns


# In[2]:


df = read_csv('/Users/victorflores/Documents/PAPERS2023/Paper_Applied_Science/Data/Drift17_09_2023_sinX6_X7.csv')


# In[3]:


df.head().T


# In[4]:


df = df.dropna()


# In[ ]:





# In[6]:


df.head(100)


# In[7]:


df1 = df.drop('Y', axis=1)


# In[8]:


df1.info()


# In[9]:


labels = ['X1', 'X2', 'X3', 'X4', 'X5', 'X8', 'X9']


# In[27]:



sns.set_theme(style="white")
corr = df1.corr()
mask = np.triu(df1.corr())
f, ax = plt.subplots(figsize=(10, 10))

ax.xaxis.set_tick_params(labelsize=18)
ax.yaxis.set_tick_params(labelsize=18)
cmap = sns.color_palette("Blues",25)

sns.heatmap(corr,
            xticklabels=labels, 
            yticklabels=labels,
            mask=mask, 
            cmap=cmap, 
            vmax=1, 
            center=0,
            square=True, 
            linewidths=5, 
            cbar_kws={"shrink": .7}
           )

plt.savefig("Fig-5-IEEE-LAT.png", dpi=600)


